function sData = reduceData(sData)
	%UNTITLED Summary of this function goes here
	%   Detailed explanation goes here
	%{
	cellRemFields = {'cellLGN_OFF',...
		'cellLGN_ON',...
		'cellR_OFF',...
		'cellR_ON',...
		'cellSpikeTimesLGN_OFF',...
		'cellSpikeTimesLGN_ON',...
		'cellSpikeTimesCortex',...
		'matFieldsV2',...
		'matPrefGabors',...
		'matSynConnOFF_to_Cort',...
		'matSynConnON_to_Cort',...
		'vecSynConductance',...
		'vecSynConductanceOFF_to_Cort',...
		'vecSynConductanceON_to_Cort',...
		'vecSynDelay',...
		'vecSynDelayOFF_to_Cort',...
		'vecSynDelayON_to_Cort',...
		'vecSynExcInh',...
		'vecSynType',...
		'vecSynWeight',...
		'vecSynWeightOFF_to_Cort',...
		'vecSynWeightON_to_Cort'};
%}
	cellRemFields = {'cellLGN_OFF',...
		'cellLGN_ON',...
		'cellR_OFF',...
		'cellR_ON',...
		'cellSpikeTimesLGN_OFF',...
		'cellSpikeTimesLGN_ON',...
		'cellSpikeTimesCortex',...
		'matFieldsV2',...
		'matPrefGabors',...
		'matSynConnOFF_to_Cort',...
		'matSynConnON_to_Cort',...
		'vecSynConductanceOFF_to_Cort',...
		'vecSynConductanceON_to_Cort',...
		'vecSynDelayOFF_to_Cort',...
		'vecSynDelayON_to_Cort',...
		'vecSynWeightOFF_to_Cort',...
		'vecSynWeightON_to_Cort'};

	cellFields = fieldnames(sData);
	indFields = ismember(cellRemFields,cellFields);
	sData = rmfield(sData,cellRemFields(indFields));
end

