function PMAL_ReceptiveField(sessionData,trialData,spikeData)

%% Analysis of Receptive Field





%% Receptive Field

%Calculate STA of stimulus right before spiking of the cell. Average this 
%over conditions and one gets receptive field perhaps.

% So I will need a proxy of the location in time and for all those times 
% whether there was a spike or not... Location can be dissected into X and
% Y perhaps and then fused again?
% There is not one x and one y + you have intensity. 
% Perhaps you can make a STA per pixel... Only sharp onset of yes or no

% perhaps different latencies per response orientation. 

% Neill and Stryker, 2011:
% Receptive field size was calculated from 4 × 8° light bars. Bars were swept
% across the visual field at eight locations along the axis perpendicular to
% the direction of motion, e.g., for horizontally moving bars, each presentation
%     swept a bar across at a different vertical position. The responses from
%     the eight sweeps were binned at 100 ms and used to construct firing rate
%     as a function of bar position. This was fitted with a two-dimensional
%     Gaussian, with independent widths ?x and ?y, and RF radius was calculated
%     by averaging the half-width at half-maximum of the two axes of the
%     Gaussian fit (equivalent to the semi-major and semi-minor axes of the
%     ellipse generated by the half-maximum contour). This process was repeated
%     for four different directions and averaged across all conditions that
%         gave a sufficient response. The bar length, 8°, was chosen to elicit
%         strong responses from as many units as possible. However, it puts a
%         lower limit on our measurement of RF size, ~4°, so we may have
%         overestimated the size of the smallest receptive fields.
    
[avg, nEvs] = ScreenTrigAvg(events, stim, windowSize);



end
